/* generated by engine/lib/ttlib.py::generate_tt_wrapper - do not hand-edit; regenerate from spec.yaml's tt_pins instead. */
`default_nettype none

module tt_um_r2r_dac_digital (
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    inout  wire [7:0] ua,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
  wire w_clk;
  assign w_clk = clk;
  wire [7:0] w_dac_code;
  wire w_ena;
  assign w_ena = ena;
  wire [1:0] w_mode;
  assign w_mode = uio_in[1:0];
  wire w_rst_n;
  assign w_rst_n = rst_n;
  wire w_slow;
  assign w_slow = uio_in[2];
  wire [7:0] w_ui_in;
  assign w_ui_in = ui_in[7:0];
  wire [7:0] w_uo_out;

  r2r_dac_digital u_r2r_dac_digital (
      .clk(w_clk),
      .dac_code(w_dac_code),
      .ena(w_ena),
      .mode(w_mode),
      .rst_n(w_rst_n),
      .slow(w_slow),
      .ui_in(w_ui_in),
      .uo_out(w_uo_out)
  );

  r2r_dac_analog u_analog (
      .dac_code(w_dac_code),
      .vout(ua[0])
  );

  assign uo_out = {w_uo_out[7], w_uo_out[6], w_uo_out[5], w_uo_out[4], w_uo_out[3], w_uo_out[2], w_uo_out[1], w_uo_out[0]};
  assign uio_out = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0};
  assign uio_oe = 8'b00000000;
  wire _unused = &{ena, uio_in[3], uio_in[4], uio_in[5], uio_in[6], uio_in[7], 1'b0};
endmodule
`default_nettype wire
