/* Generated by Yosys 0.69 (git sha1 9f75ca1f9, Release, GNU /usr/bin/c++ 13.3.0) */

module tt_um_r2r_dac_digital(ui_in, uo_out, uio_in, uio_out, uio_oe, ua, ena, clk, rst_n);
  input [7:0] ui_in;
  wire [7:0] ui_in;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  inout [7:0] ua;
  wire [7:0] ua;
  input ena;
  wire ena;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire \u_r2r_dac_digital.cnt[0] ;
  wire \u_r2r_dac_digital.cnt[1] ;
  wire \u_r2r_dac_digital.cnt[2] ;
  wire \u_r2r_dac_digital.cnt[3] ;
  wire \u_r2r_dac_digital.cnt[4] ;
  wire \u_r2r_dac_digital.cnt[5] ;
  wire \u_r2r_dac_digital.cnt[6] ;
  wire \u_r2r_dac_digital.cnt[7] ;
  wire \u_r2r_dac_digital.code_reg[0] ;
  wire \u_r2r_dac_digital.code_reg[1] ;
  wire \u_r2r_dac_digital.code_reg[2] ;
  wire \u_r2r_dac_digital.code_reg[3] ;
  wire \u_r2r_dac_digital.code_reg[4] ;
  wire \u_r2r_dac_digital.code_reg[5] ;
  wire \u_r2r_dac_digital.code_reg[6] ;
  wire \u_r2r_dac_digital.code_reg[7] ;
  wire \u_r2r_dac_digital.presc[0] ;
  wire \u_r2r_dac_digital.presc[1] ;
  wire \u_r2r_dac_digital.presc[2] ;
  wire \u_r2r_dac_digital.presc[3] ;
  wire \u_r2r_dac_digital.presc[4] ;
  wire \u_r2r_dac_digital.presc[5] ;
  wire \u_r2r_dac_digital.presc[6] ;
  wire \u_r2r_dac_digital.presc[7] ;
  wire \u_r2r_dac_digital.sine_val[0] ;
  wire \u_r2r_dac_digital.sine_val[1] ;
  wire \u_r2r_dac_digital.sine_val[2] ;
  wire \u_r2r_dac_digital.sine_val[3] ;
  wire \u_r2r_dac_digital.sine_val[4] ;
  wire \u_r2r_dac_digital.sine_val[5] ;
  wire \u_r2r_dac_digital.sine_val[6] ;
  wire \u_r2r_dac_digital.sine_val[7] ;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _309_ (
    .I(\u_r2r_dac_digital.cnt[7] ),
    .ZN(_294_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _310_ (
    .I(\u_r2r_dac_digital.cnt[6] ),
    .ZN(_295_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _311_ (
    .I(\u_r2r_dac_digital.cnt[5] ),
    .ZN(_296_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _312_ (
    .I(\u_r2r_dac_digital.cnt[4] ),
    .ZN(_297_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _313_ (
    .I(\u_r2r_dac_digital.cnt[3] ),
    .ZN(_298_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _314_ (
    .I(\u_r2r_dac_digital.cnt[2] ),
    .ZN(_299_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _315_ (
    .I(\u_r2r_dac_digital.cnt[1] ),
    .ZN(_300_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _316_ (
    .I(\u_r2r_dac_digital.cnt[0] ),
    .ZN(_301_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _317_ (
    .I(\u_r2r_dac_digital.presc[3] ),
    .ZN(_302_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _318_ (
    .I(\u_r2r_dac_digital.presc[6] ),
    .ZN(_303_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _319_ (
    .I(\u_r2r_dac_digital.presc[7] ),
    .ZN(_304_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _320_ (
    .I(uio_in[2]),
    .ZN(_305_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _321_ (
    .I(uio_in[1]),
    .ZN(_306_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _322_ (
    .I(uio_in[0]),
    .ZN(_307_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _323_ (
    .I(rst_n),
    .ZN(_308_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _324_ (
    .A1(\u_r2r_dac_digital.presc[1] ),
    .A2(\u_r2r_dac_digital.presc[0] ),
    .A3(\u_r2r_dac_digital.presc[2] ),
    .ZN(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _325_ (
    .A1(\u_r2r_dac_digital.presc[1] ),
    .A2(\u_r2r_dac_digital.presc[0] ),
    .A3(\u_r2r_dac_digital.presc[2] ),
    .A4(\u_r2r_dac_digital.presc[3] ),
    .Z(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _326_ (
    .A1(\u_r2r_dac_digital.presc[4] ),
    .A2(\u_r2r_dac_digital.presc[5] ),
    .A3(_041_),
    .ZN(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _327_ (
    .A1(\u_r2r_dac_digital.presc[4] ),
    .A2(\u_r2r_dac_digital.presc[5] ),
    .A3(\u_r2r_dac_digital.presc[6] ),
    .A4(_041_),
    .Z(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _328_ (
    .A1(\u_r2r_dac_digital.presc[4] ),
    .A2(\u_r2r_dac_digital.presc[5] ),
    .A3(\u_r2r_dac_digital.presc[6] ),
    .A4(_041_),
    .ZN(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _329_ (
    .A1(\u_r2r_dac_digital.presc[7] ),
    .A2(_043_),
    .B(_305_),
    .ZN(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _330_ (
    .A1(_304_),
    .A2(_044_),
    .B(uio_in[2]),
    .ZN(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _331_ (
    .A1(_300_),
    .A2(_301_),
    .ZN(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _332_ (
    .A1(\u_r2r_dac_digital.cnt[1] ),
    .A2(\u_r2r_dac_digital.cnt[0] ),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _333_ (
    .A1(_045_),
    .A2(_048_),
    .ZN(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _334_ (
    .A1(_299_),
    .A2(_048_),
    .ZN(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _335_ (
    .A1(\u_r2r_dac_digital.cnt[2] ),
    .A2(_047_),
    .ZN(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _336_ (
    .A1(_045_),
    .A2(_051_),
    .ZN(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _337_ (
    .A1(_046_),
    .A2(_050_),
    .ZN(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _338_ (
    .A1(\u_r2r_dac_digital.cnt[3] ),
    .A2(_046_),
    .A3(_050_),
    .ZN(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _339_ (
    .A1(_297_),
    .A2(_298_),
    .A3(_045_),
    .A4(_051_),
    .ZN(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _340_ (
    .A1(\u_r2r_dac_digital.cnt[4] ),
    .A2(\u_r2r_dac_digital.cnt[3] ),
    .A3(_046_),
    .A4(_050_),
    .ZN(_056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _341_ (
    .A1(\u_r2r_dac_digital.cnt[5] ),
    .A2(_055_),
    .ZN(_057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _342_ (
    .A1(\u_r2r_dac_digital.cnt[6] ),
    .A2(\u_r2r_dac_digital.cnt[5] ),
    .A3(_055_),
    .ZN(_058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _343_ (
    .A1(_294_),
    .A2(_058_),
    .ZN(_059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _344_ (
    .A1(_294_),
    .A2(_058_),
    .Z(_060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _345_ (
    .A1(rst_n),
    .A2(_059_),
    .A3(_060_),
    .ZN(_061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _346_ (
    .I(_061_),
    .ZN(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _347_ (
    .A1(_296_),
    .A2(_056_),
    .ZN(_062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _348_ (
    .A1(rst_n),
    .A2(_057_),
    .A3(_062_),
    .ZN(_063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _349_ (
    .I(_063_),
    .ZN(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _350_ (
    .A1(_296_),
    .A2(_056_),
    .B(_295_),
    .ZN(_064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _351_ (
    .A1(rst_n),
    .A2(_058_),
    .A3(_064_),
    .ZN(_065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _352_ (
    .I(_065_),
    .ZN(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _353_ (
    .A1(_063_),
    .A2(_032_),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _354_ (
    .I(_066_),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _355_ (
    .A1(_298_),
    .A2(_045_),
    .A3(_051_),
    .B(_297_),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _356_ (
    .A1(rst_n),
    .A2(_056_),
    .A3(_068_),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _357_ (
    .I(_069_),
    .ZN(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _358_ (
    .A1(_045_),
    .A2(_051_),
    .B(_298_),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _359_ (
    .A1(rst_n),
    .A2(_054_),
    .A3(_070_),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _360_ (
    .I(_071_),
    .ZN(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _361_ (
    .A1(_297_),
    .A2(rst_n),
    .A3(_054_),
    .A4(_070_),
    .Z(_072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _362_ (
    .A1(\u_r2r_dac_digital.cnt[0] ),
    .A2(_046_),
    .ZN(_073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _363_ (
    .A1(\u_r2r_dac_digital.cnt[0] ),
    .A2(_046_),
    .B(\u_r2r_dac_digital.cnt[1] ),
    .ZN(_074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _364_ (
    .A1(_301_),
    .A2(_045_),
    .B(_300_),
    .ZN(_075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _365_ (
    .A1(_046_),
    .A2(_047_),
    .B(_308_),
    .ZN(_076_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _366_ (
    .A1(_045_),
    .A2(_048_),
    .B(rst_n),
    .ZN(_077_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _367_ (
    .A1(_074_),
    .A2(_077_),
    .ZN(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _368_ (
    .A1(_301_),
    .A2(_045_),
    .B(_308_),
    .ZN(_078_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _369_ (
    .A1(_301_),
    .A2(_045_),
    .Z(_079_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _370_ (
    .A1(\u_r2r_dac_digital.cnt[0] ),
    .A2(_045_),
    .Z(_080_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _371_ (
    .A1(rst_n),
    .A2(_079_),
    .ZN(_081_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _372_ (
    .I(_081_),
    .ZN(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _373_ (
    .A1(_308_),
    .A2(_049_),
    .A3(_074_),
    .A4(_079_),
    .ZN(_082_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _374_ (
    .A1(_027_),
    .A2(_081_),
    .ZN(_083_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _375_ (
    .A1(_300_),
    .A2(_077_),
    .B(_078_),
    .C(_073_),
    .ZN(_084_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _376_ (
    .A1(_075_),
    .A2(_076_),
    .B1(_079_),
    .B2(rst_n),
    .ZN(_085_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _377_ (
    .A1(_074_),
    .A2(_077_),
    .B1(_080_),
    .B2(_308_),
    .ZN(_086_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _378_ (
    .A1(_308_),
    .A2(_049_),
    .A3(_074_),
    .A4(_080_),
    .ZN(_087_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _379_ (
    .A1(\u_r2r_dac_digital.cnt[1] ),
    .A2(_073_),
    .A3(_076_),
    .A4(_078_),
    .ZN(_088_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _380_ (
    .A1(_086_),
    .A2(_088_),
    .ZN(_089_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _381_ (
    .A1(_030_),
    .A2(_071_),
    .A3(_089_),
    .ZN(_090_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _382_ (
    .A1(_046_),
    .A2(_047_),
    .B(\u_r2r_dac_digital.cnt[2] ),
    .ZN(_091_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _383_ (
    .A1(_045_),
    .A2(_048_),
    .B(_299_),
    .ZN(_092_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _384_ (
    .A1(_046_),
    .A2(_050_),
    .B(_308_),
    .ZN(_093_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _385_ (
    .A1(_045_),
    .A2(_051_),
    .B(rst_n),
    .ZN(_094_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _386_ (
    .A1(_092_),
    .A2(_093_),
    .ZN(_095_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _387_ (
    .I(_095_),
    .ZN(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _388_ (
    .A1(_082_),
    .A2(_095_),
    .Z(_096_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _389_ (
    .A1(_029_),
    .A2(_096_),
    .B(_030_),
    .ZN(_097_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _390_ (
    .A1(_075_),
    .A2(_076_),
    .B1(_092_),
    .B2(_093_),
    .ZN(_098_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _391_ (
    .A1(_074_),
    .A2(_077_),
    .B1(_091_),
    .B2(_094_),
    .ZN(_099_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _392_ (
    .A1(_071_),
    .A2(_098_),
    .ZN(_100_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _393_ (
    .A1(_029_),
    .A2(_099_),
    .ZN(_101_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _394_ (
    .A1(_086_),
    .A2(_028_),
    .ZN(_102_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _395_ (
    .A1(_071_),
    .A2(_083_),
    .B1(_100_),
    .B2(_102_),
    .C(_097_),
    .ZN(_103_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _396_ (
    .A1(_075_),
    .A2(_076_),
    .B(_091_),
    .C(_094_),
    .ZN(_104_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _397_ (
    .A1(_029_),
    .A2(_104_),
    .Z(_105_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _398_ (
    .A1(_083_),
    .A2(_105_),
    .B(_030_),
    .ZN(_106_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _399_ (
    .A1(_053_),
    .A2(_092_),
    .B(_080_),
    .C(_308_),
    .ZN(_107_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _400_ (
    .A1(_052_),
    .A2(_091_),
    .B(_079_),
    .C(rst_n),
    .ZN(_108_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _401_ (
    .A1(_071_),
    .A2(_027_),
    .ZN(_109_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _402_ (
    .A1(_071_),
    .A2(_087_),
    .A3(_107_),
    .B(_105_),
    .ZN(_110_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _403_ (
    .A1(_308_),
    .A2(_052_),
    .A3(_079_),
    .A4(_091_),
    .ZN(_111_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _404_ (
    .A1(rst_n),
    .A2(_053_),
    .A3(_080_),
    .A4(_092_),
    .ZN(_112_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _405_ (
    .A1(_069_),
    .A2(_111_),
    .ZN(_113_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _406_ (
    .A1(_063_),
    .A2(_106_),
    .A3(_110_),
    .A4(_113_),
    .Z(_114_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _407_ (
    .A1(_086_),
    .A2(_088_),
    .B(_095_),
    .ZN(_115_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _408_ (
    .A1(_071_),
    .A2(_108_),
    .ZN(_116_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _409_ (
    .A1(_029_),
    .A2(_081_),
    .B(_069_),
    .ZN(_117_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _410_ (
    .A1(_115_),
    .A2(_116_),
    .B(_117_),
    .C(_031_),
    .ZN(_118_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _411_ (
    .A1(_107_),
    .A2(_111_),
    .ZN(_119_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _412_ (
    .A1(_029_),
    .A2(_086_),
    .ZN(_120_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _413_ (
    .A1(_085_),
    .A2(_095_),
    .B(_029_),
    .ZN(_121_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _414_ (
    .A1(_085_),
    .A2(_095_),
    .B(_104_),
    .C(_029_),
    .ZN(_122_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _415_ (
    .A1(_100_),
    .A2(_119_),
    .B(_122_),
    .ZN(_123_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _416_ (
    .A1(_031_),
    .A2(_069_),
    .ZN(_124_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _417_ (
    .A1(_123_),
    .A2(_124_),
    .B(_032_),
    .C(_118_),
    .ZN(_125_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _418_ (
    .A1(_067_),
    .A2(_090_),
    .A3(_103_),
    .B1(_114_),
    .B2(_125_),
    .ZN(_126_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _419_ (
    .A1(_031_),
    .A2(_032_),
    .ZN(_127_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _420_ (
    .A1(_063_),
    .A2(_065_),
    .ZN(_128_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _421_ (
    .A1(_082_),
    .A2(_095_),
    .B(_084_),
    .C(_072_),
    .ZN(_129_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _422_ (
    .A1(_087_),
    .A2(_095_),
    .B(_071_),
    .C(_085_),
    .ZN(_130_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _423_ (
    .A1(_108_),
    .A2(_112_),
    .B(_029_),
    .C(_104_),
    .ZN(_131_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _424_ (
    .A1(_069_),
    .A2(_130_),
    .A3(_131_),
    .B(_129_),
    .ZN(_132_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _425_ (
    .A1(_069_),
    .A2(_071_),
    .A3(_081_),
    .ZN(_133_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _426_ (
    .I(_133_),
    .ZN(_134_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _427_ (
    .A1(_132_),
    .A2(_134_),
    .B(_127_),
    .ZN(_135_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _428_ (
    .A1(_099_),
    .A2(_132_),
    .ZN(_136_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _429_ (
    .A1(_135_),
    .A2(_136_),
    .ZN(_137_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _430_ (
    .A1(_126_),
    .A2(_137_),
    .B(_033_),
    .ZN(_138_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _431_ (
    .A1(_061_),
    .A2(_135_),
    .ZN(_139_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _432_ (
    .A1(_126_),
    .A2(_139_),
    .B(_138_),
    .ZN(_000_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _433_ (
    .A1(_299_),
    .A2(_074_),
    .A3(_077_),
    .ZN(_140_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _434_ (
    .A1(\u_r2r_dac_digital.cnt[2] ),
    .A2(_075_),
    .A3(_076_),
    .ZN(_141_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _435_ (
    .A1(_088_),
    .A2(_095_),
    .ZN(_142_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _436_ (
    .A1(_087_),
    .A2(_028_),
    .ZN(_143_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _437_ (
    .A1(_087_),
    .A2(_028_),
    .B(_029_),
    .ZN(_144_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _438_ (
    .A1(_088_),
    .A2(_095_),
    .B(_071_),
    .ZN(_145_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _439_ (
    .A1(_085_),
    .A2(_087_),
    .A3(_095_),
    .ZN(_146_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _440_ (
    .A1(_086_),
    .A2(_088_),
    .A3(_028_),
    .ZN(_147_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _441_ (
    .A1(_100_),
    .A2(_147_),
    .B(_144_),
    .C(_030_),
    .ZN(_148_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _442_ (
    .A1(_029_),
    .A2(_098_),
    .ZN(_149_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _443_ (
    .A1(_029_),
    .A2(_098_),
    .A3(_107_),
    .A4(_111_),
    .ZN(_150_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _444_ (
    .A1(_119_),
    .A2(_149_),
    .ZN(_151_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _445_ (
    .A1(_117_),
    .A2(_151_),
    .B(_148_),
    .C(_031_),
    .ZN(_152_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _446_ (
    .A1(_096_),
    .A2(_146_),
    .B(_071_),
    .ZN(_153_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _447_ (
    .A1(_087_),
    .A2(_028_),
    .ZN(_154_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _448_ (
    .A1(_088_),
    .A2(_095_),
    .ZN(_155_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _449_ (
    .A1(_086_),
    .A2(_088_),
    .A3(_095_),
    .ZN(_156_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _450_ (
    .A1(_071_),
    .A2(_104_),
    .ZN(_157_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _451_ (
    .A1(_156_),
    .A2(_157_),
    .B(_030_),
    .ZN(_158_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _452_ (
    .A1(_069_),
    .A2(_027_),
    .A3(_150_),
    .ZN(_159_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _453_ (
    .A1(_153_),
    .A2(_158_),
    .B(_159_),
    .C(_063_),
    .ZN(_160_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _454_ (
    .A1(_071_),
    .A2(_083_),
    .B(_100_),
    .C(_111_),
    .ZN(_161_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _455_ (
    .A1(_072_),
    .A2(_096_),
    .Z(_162_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _456_ (
    .A1(_069_),
    .A2(_161_),
    .B(_133_),
    .C(_066_),
    .ZN(_163_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _457_ (
    .A1(_065_),
    .A2(_152_),
    .A3(_160_),
    .B1(_162_),
    .B2(_163_),
    .ZN(_164_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _458_ (
    .A1(_087_),
    .A2(_119_),
    .B(_029_),
    .ZN(_165_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _459_ (
    .A1(_029_),
    .A2(_140_),
    .ZN(_166_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _460_ (
    .A1(_071_),
    .A2(_141_),
    .ZN(_167_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _461_ (
    .A1(_029_),
    .A2(_089_),
    .ZN(_168_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _462_ (
    .A1(_071_),
    .A2(_086_),
    .A3(_088_),
    .A4(_141_),
    .ZN(_169_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _463_ (
    .A1(_030_),
    .A2(_165_),
    .A3(_169_),
    .ZN(_170_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _464_ (
    .A1(_086_),
    .A2(_095_),
    .B(_088_),
    .C(_071_),
    .ZN(_171_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _465_ (
    .A1(_120_),
    .A2(_142_),
    .B(_171_),
    .C(_069_),
    .ZN(_172_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _466_ (
    .A1(_170_),
    .A2(_172_),
    .B(_128_),
    .ZN(_173_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _467_ (
    .A1(_164_),
    .A2(_173_),
    .B(_033_),
    .ZN(_174_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _468_ (
    .A1(_029_),
    .A2(_089_),
    .B1(_120_),
    .B2(_142_),
    .C(_069_),
    .ZN(_175_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _469_ (
    .A1(_170_),
    .A2(_175_),
    .B(_128_),
    .ZN(_176_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _470_ (
    .A1(_033_),
    .A2(_164_),
    .A3(_176_),
    .B(_174_),
    .ZN(_001_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _471_ (
    .A1(_101_),
    .A2(_111_),
    .A3(_146_),
    .B(_069_),
    .ZN(_177_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _472_ (
    .A1(_030_),
    .A2(_099_),
    .A3(_144_),
    .ZN(_178_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _473_ (
    .A1(_168_),
    .A2(_177_),
    .B(_178_),
    .ZN(_179_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _474_ (
    .A1(_098_),
    .A2(_107_),
    .A3(_111_),
    .B(_029_),
    .ZN(_180_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _475_ (
    .A1(_169_),
    .A2(_180_),
    .B(_063_),
    .ZN(_181_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _476_ (
    .A1(_100_),
    .A2(_143_),
    .B(_031_),
    .ZN(_182_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _477_ (
    .A1(_147_),
    .A2(_149_),
    .B(_031_),
    .C(_109_),
    .ZN(_183_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _478_ (
    .A1(_063_),
    .A2(_119_),
    .B(_030_),
    .ZN(_184_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _479_ (
    .A1(_030_),
    .A2(_181_),
    .A3(_182_),
    .B1(_183_),
    .B2(_184_),
    .ZN(_185_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _480_ (
    .A1(_066_),
    .A2(_179_),
    .B1(_185_),
    .B2(_032_),
    .ZN(_186_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _481_ (
    .A1(_156_),
    .A2(_157_),
    .B(_097_),
    .ZN(_187_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _482_ (
    .A1(_069_),
    .A2(_096_),
    .B(_187_),
    .ZN(_188_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _483_ (
    .A1(_128_),
    .A2(_188_),
    .B(_186_),
    .ZN(_189_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _484_ (
    .A1(_131_),
    .A2(_162_),
    .A3(_187_),
    .B(_127_),
    .ZN(_190_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _485_ (
    .A1(_033_),
    .A2(_190_),
    .Z(_191_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _486_ (
    .A1(_061_),
    .A2(_189_),
    .B1(_191_),
    .B2(_186_),
    .ZN(_002_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _487_ (
    .A1(_029_),
    .A2(_140_),
    .ZN(_192_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _488_ (
    .A1(_071_),
    .A2(_155_),
    .B(_192_),
    .C(_069_),
    .ZN(_193_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _489_ (
    .A1(_102_),
    .A2(_121_),
    .B(_193_),
    .ZN(_194_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _490_ (
    .A1(_085_),
    .A2(_087_),
    .A3(_028_),
    .B(_141_),
    .ZN(_195_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _491_ (
    .A1(_071_),
    .A2(_195_),
    .Z(_196_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _492_ (
    .A1(_069_),
    .A2(_196_),
    .ZN(_197_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _493_ (
    .A1(_194_),
    .A2(_197_),
    .B(_031_),
    .ZN(_198_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _494_ (
    .A1(_085_),
    .A2(_095_),
    .B(_071_),
    .ZN(_199_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _495_ (
    .A1(_071_),
    .A2(_098_),
    .A3(_140_),
    .B(_199_),
    .ZN(_200_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _496_ (
    .A1(_072_),
    .A2(_142_),
    .B1(_200_),
    .B2(_030_),
    .C(_031_),
    .ZN(_201_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _497_ (
    .A1(_065_),
    .A2(_201_),
    .ZN(_202_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _498_ (
    .A1(_198_),
    .A2(_202_),
    .Z(_203_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _499_ (
    .A1(\u_r2r_dac_digital.cnt[3] ),
    .A2(_028_),
    .ZN(_204_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _500_ (
    .A1(_088_),
    .A2(_095_),
    .B1(_145_),
    .B2(_204_),
    .C(_030_),
    .ZN(_205_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _501_ (
    .A1(_069_),
    .A2(_029_),
    .A3(_099_),
    .ZN(_206_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _502_ (
    .A1(_205_),
    .A2(_206_),
    .B(_066_),
    .ZN(_207_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _503_ (
    .I(_207_),
    .ZN(_208_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _504_ (
    .A1(_028_),
    .A2(_120_),
    .B(_030_),
    .ZN(_209_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _505_ (
    .A1(_028_),
    .A2(_120_),
    .B1(_154_),
    .B2(_167_),
    .C(_030_),
    .ZN(_210_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _506_ (
    .A1(_088_),
    .A2(_095_),
    .B(_071_),
    .ZN(_211_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _507_ (
    .A1(_071_),
    .A2(_195_),
    .B1(_211_),
    .B2(_141_),
    .ZN(_212_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _508_ (
    .A1(_030_),
    .A2(_212_),
    .Z(_213_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _509_ (
    .A1(_210_),
    .A2(_213_),
    .B(_128_),
    .ZN(_214_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _510_ (
    .A1(_198_),
    .A2(_202_),
    .B(_208_),
    .C(_214_),
    .ZN(_215_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _511_ (
    .A1(_155_),
    .A2(_166_),
    .B1(_193_),
    .B2(_209_),
    .C(_128_),
    .ZN(_216_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _512_ (
    .A1(_061_),
    .A2(_207_),
    .ZN(_217_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _513_ (
    .A1(_203_),
    .A2(_216_),
    .A3(_217_),
    .B1(_215_),
    .B2(_061_),
    .ZN(_003_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _514_ (
    .A1(_030_),
    .A2(_211_),
    .Z(_218_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _515_ (
    .A1(_030_),
    .A2(_211_),
    .B(_031_),
    .ZN(_219_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _516_ (
    .A1(_099_),
    .A2(_141_),
    .B(_107_),
    .C(_029_),
    .ZN(_220_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _517_ (
    .A1(_029_),
    .A2(_154_),
    .B(_220_),
    .ZN(_221_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _518_ (
    .A1(_199_),
    .A2(_219_),
    .B1(_221_),
    .B2(_030_),
    .ZN(_222_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _519_ (
    .A1(_030_),
    .A2(_192_),
    .A3(_199_),
    .ZN(_223_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _520_ (
    .A1(_063_),
    .A2(_223_),
    .B(_222_),
    .C(_065_),
    .ZN(_224_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _521_ (
    .A1(_071_),
    .A2(_154_),
    .ZN(_225_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _522_ (
    .A1(_031_),
    .A2(_069_),
    .A3(_204_),
    .A4(_225_),
    .ZN(_226_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _523_ (
    .A1(\u_r2r_dac_digital.cnt[3] ),
    .A2(_030_),
    .A3(_028_),
    .ZN(_227_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _524_ (
    .A1(_069_),
    .A2(_029_),
    .A3(_140_),
    .ZN(_228_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _525_ (
    .A1(_031_),
    .A2(_228_),
    .ZN(_229_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _526_ (
    .A1(_030_),
    .A2(_221_),
    .B(_227_),
    .C(_229_),
    .ZN(_230_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _527_ (
    .A1(_226_),
    .A2(_230_),
    .B(_032_),
    .ZN(_231_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _528_ (
    .A1(_224_),
    .A2(_231_),
    .B(_033_),
    .ZN(_232_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _529_ (
    .A1(_166_),
    .A2(_218_),
    .B(_227_),
    .C(_229_),
    .ZN(_233_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _530_ (
    .A1(_226_),
    .A2(_233_),
    .B(_032_),
    .ZN(_234_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _531_ (
    .A1(_033_),
    .A2(_224_),
    .A3(_234_),
    .B(_232_),
    .ZN(_004_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _532_ (
    .A1(_029_),
    .A2(_154_),
    .B(_121_),
    .C(_030_),
    .ZN(_235_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _533_ (
    .A1(_128_),
    .A2(_228_),
    .A3(_235_),
    .ZN(_236_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _534_ (
    .A1(_069_),
    .A2(_192_),
    .B(_063_),
    .ZN(_237_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _535_ (
    .A1(_032_),
    .A2(_237_),
    .ZN(_238_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _536_ (
    .A1(_124_),
    .A2(_225_),
    .Z(_239_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _537_ (
    .A1(_065_),
    .A2(_219_),
    .ZN(_240_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _538_ (
    .A1(_030_),
    .A2(_167_),
    .ZN(_241_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _539_ (
    .A1(_238_),
    .A2(_239_),
    .B1(_240_),
    .B2(_241_),
    .ZN(_242_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _540_ (
    .A1(_236_),
    .A2(_242_),
    .B(_033_),
    .ZN(_243_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _541_ (
    .A1(_218_),
    .A2(_241_),
    .B(_128_),
    .ZN(_244_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _542_ (
    .A1(_033_),
    .A2(_242_),
    .A3(_244_),
    .B(_243_),
    .ZN(_005_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _543_ (
    .A1(_127_),
    .A2(_241_),
    .B(_240_),
    .ZN(_245_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _544_ (
    .A1(_098_),
    .A2(_134_),
    .B(_061_),
    .ZN(_246_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _545_ (
    .I0(_246_),
    .I1(_061_),
    .S(_245_),
    .Z(_006_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _546_ (
    .A1(rst_n),
    .A2(_044_),
    .ZN(_247_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _547_ (
    .A1(_303_),
    .A2(_042_),
    .B(_247_),
    .ZN(_007_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _548_ (
    .A1(_304_),
    .A2(_044_),
    .B(rst_n),
    .ZN(_248_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _549_ (
    .A1(_304_),
    .A2(_044_),
    .B(_248_),
    .ZN(_008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _550_ (
    .A1(_033_),
    .A2(_128_),
    .B(_246_),
    .ZN(_009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _551_ (
    .A1(_306_),
    .A2(uio_in[0]),
    .ZN(_249_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _552_ (
    .A1(uio_in[1]),
    .A2(_307_),
    .ZN(_250_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _553_ (
    .A1(_306_),
    .A2(_307_),
    .ZN(_251_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _554_ (
    .A1(uio_in[1]),
    .A2(uio_in[0]),
    .ZN(_252_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _555_ (
    .A1(_306_),
    .A2(_307_),
    .ZN(_253_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _556_ (
    .A1(ui_in[0]),
    .A2(_252_),
    .ZN(_254_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _557_ (
    .A1(\u_r2r_dac_digital.sine_val[0] ),
    .A2(_249_),
    .B1(_251_),
    .B2(\u_r2r_dac_digital.code_reg[0] ),
    .ZN(_255_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _558_ (
    .A1(\u_r2r_dac_digital.cnt[0] ),
    .A2(_250_),
    .B1(_252_),
    .B2(ui_in[0]),
    .ZN(_256_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _559_ (
    .A1(_255_),
    .A2(_256_),
    .B(_308_),
    .ZN(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _560_ (
    .A1(ui_in[1]),
    .A2(_252_),
    .ZN(_257_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _561_ (
    .A1(\u_r2r_dac_digital.sine_val[1] ),
    .A2(_249_),
    .B1(_250_),
    .B2(\u_r2r_dac_digital.cnt[1] ),
    .ZN(_258_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _562_ (
    .A1(\u_r2r_dac_digital.code_reg[1] ),
    .A2(_251_),
    .B1(_252_),
    .B2(ui_in[1]),
    .ZN(_259_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _563_ (
    .A1(_258_),
    .A2(_259_),
    .B(_308_),
    .ZN(_011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _564_ (
    .A1(\u_r2r_dac_digital.cnt[2] ),
    .A2(_250_),
    .B1(_251_),
    .B2(\u_r2r_dac_digital.code_reg[2] ),
    .ZN(_260_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _565_ (
    .A1(ui_in[2]),
    .A2(_252_),
    .ZN(_261_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _566_ (
    .A1(\u_r2r_dac_digital.sine_val[2] ),
    .A2(_249_),
    .B1(_252_),
    .B2(ui_in[2]),
    .ZN(_262_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _567_ (
    .A1(_260_),
    .A2(_262_),
    .B(_308_),
    .ZN(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _568_ (
    .A1(ui_in[3]),
    .A2(_252_),
    .ZN(_263_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _569_ (
    .A1(\u_r2r_dac_digital.sine_val[3] ),
    .A2(_249_),
    .B1(_251_),
    .B2(\u_r2r_dac_digital.code_reg[3] ),
    .ZN(_264_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _570_ (
    .A1(\u_r2r_dac_digital.cnt[3] ),
    .A2(_250_),
    .B1(_252_),
    .B2(ui_in[3]),
    .ZN(_265_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _571_ (
    .A1(_264_),
    .A2(_265_),
    .B(_308_),
    .ZN(_013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _572_ (
    .A1(ui_in[4]),
    .A2(_252_),
    .ZN(_266_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _573_ (
    .A1(\u_r2r_dac_digital.sine_val[4] ),
    .A2(_249_),
    .B1(_251_),
    .B2(\u_r2r_dac_digital.code_reg[4] ),
    .ZN(_267_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _574_ (
    .A1(\u_r2r_dac_digital.cnt[4] ),
    .A2(_250_),
    .B1(_252_),
    .B2(ui_in[4]),
    .ZN(_268_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _575_ (
    .A1(_267_),
    .A2(_268_),
    .B(_308_),
    .ZN(_014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _576_ (
    .A1(ui_in[5]),
    .A2(_252_),
    .ZN(_269_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _577_ (
    .A1(\u_r2r_dac_digital.sine_val[5] ),
    .A2(_249_),
    .B1(_250_),
    .B2(\u_r2r_dac_digital.cnt[5] ),
    .ZN(_270_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _578_ (
    .A1(\u_r2r_dac_digital.code_reg[5] ),
    .A2(_251_),
    .B1(_252_),
    .B2(ui_in[5]),
    .ZN(_271_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _579_ (
    .A1(_270_),
    .A2(_271_),
    .B(_308_),
    .ZN(_015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _580_ (
    .A1(ui_in[6]),
    .A2(_252_),
    .ZN(_272_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _581_ (
    .A1(\u_r2r_dac_digital.sine_val[6] ),
    .A2(_249_),
    .B1(_250_),
    .B2(\u_r2r_dac_digital.cnt[6] ),
    .ZN(_273_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _582_ (
    .A1(\u_r2r_dac_digital.code_reg[6] ),
    .A2(_251_),
    .B1(_252_),
    .B2(ui_in[6]),
    .ZN(_274_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _583_ (
    .A1(_273_),
    .A2(_274_),
    .B(_308_),
    .ZN(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _584_ (
    .A1(ui_in[7]),
    .A2(_252_),
    .ZN(_275_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _585_ (
    .A1(\u_r2r_dac_digital.sine_val[7] ),
    .A2(_249_),
    .B1(_250_),
    .B2(\u_r2r_dac_digital.cnt[7] ),
    .ZN(_276_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _586_ (
    .A1(\u_r2r_dac_digital.code_reg[7] ),
    .A2(_251_),
    .B1(_252_),
    .B2(ui_in[7]),
    .ZN(_277_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _587_ (
    .A1(_276_),
    .A2(_277_),
    .B(_308_),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _588_ (
    .A1(\u_r2r_dac_digital.code_reg[0] ),
    .A2(_253_),
    .ZN(_278_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _589_ (
    .A1(_254_),
    .A2(_278_),
    .B(_308_),
    .ZN(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _590_ (
    .A1(\u_r2r_dac_digital.code_reg[1] ),
    .A2(_253_),
    .ZN(_279_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _591_ (
    .A1(_257_),
    .A2(_279_),
    .B(_308_),
    .ZN(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _592_ (
    .A1(\u_r2r_dac_digital.code_reg[2] ),
    .A2(_253_),
    .ZN(_280_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _593_ (
    .A1(_261_),
    .A2(_280_),
    .B(_308_),
    .ZN(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _594_ (
    .A1(\u_r2r_dac_digital.code_reg[3] ),
    .A2(_253_),
    .ZN(_281_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _595_ (
    .A1(_263_),
    .A2(_281_),
    .B(_308_),
    .ZN(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _596_ (
    .A1(\u_r2r_dac_digital.code_reg[4] ),
    .A2(_253_),
    .ZN(_282_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _597_ (
    .A1(_266_),
    .A2(_282_),
    .B(_308_),
    .ZN(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _598_ (
    .A1(\u_r2r_dac_digital.code_reg[5] ),
    .A2(_253_),
    .ZN(_283_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _599_ (
    .A1(_269_),
    .A2(_283_),
    .B(_308_),
    .ZN(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _600_ (
    .A1(\u_r2r_dac_digital.code_reg[6] ),
    .A2(_253_),
    .ZN(_284_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _601_ (
    .A1(_272_),
    .A2(_284_),
    .B(_308_),
    .ZN(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _602_ (
    .A1(\u_r2r_dac_digital.code_reg[7] ),
    .A2(_253_),
    .ZN(_285_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _603_ (
    .A1(_275_),
    .A2(_285_),
    .B(_308_),
    .ZN(_025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _604_ (
    .A1(\u_r2r_dac_digital.presc[0] ),
    .A2(_308_),
    .ZN(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _605_ (
    .A1(\u_r2r_dac_digital.presc[1] ),
    .A2(\u_r2r_dac_digital.presc[0] ),
    .B(rst_n),
    .ZN(_286_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _606_ (
    .A1(\u_r2r_dac_digital.presc[1] ),
    .A2(\u_r2r_dac_digital.presc[0] ),
    .B(_286_),
    .ZN(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _607_ (
    .A1(\u_r2r_dac_digital.presc[1] ),
    .A2(\u_r2r_dac_digital.presc[0] ),
    .B(\u_r2r_dac_digital.presc[2] ),
    .ZN(_287_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _608_ (
    .A1(rst_n),
    .A2(_040_),
    .ZN(_288_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _609_ (
    .A1(_287_),
    .A2(_288_),
    .ZN(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _610_ (
    .A1(_302_),
    .A2(_040_),
    .ZN(_289_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _611_ (
    .A1(_308_),
    .A2(_041_),
    .ZN(_290_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _612_ (
    .A1(_289_),
    .A2(_290_),
    .Z(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _613_ (
    .A1(\u_r2r_dac_digital.presc[4] ),
    .A2(_041_),
    .B(rst_n),
    .ZN(_291_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _614_ (
    .A1(\u_r2r_dac_digital.presc[4] ),
    .A2(_041_),
    .B(_291_),
    .ZN(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _615_ (
    .A1(\u_r2r_dac_digital.presc[4] ),
    .A2(_041_),
    .B(\u_r2r_dac_digital.presc[5] ),
    .ZN(_292_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _616_ (
    .A1(rst_n),
    .A2(_042_),
    .ZN(_293_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _617_ (
    .A1(_292_),
    .A2(_293_),
    .ZN(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _618_ (
    .CLK(clk),
    .D(_000_),
    .Q(\u_r2r_dac_digital.sine_val[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _619_ (
    .CLK(clk),
    .D(_001_),
    .Q(\u_r2r_dac_digital.sine_val[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _620_ (
    .CLK(clk),
    .D(_002_),
    .Q(\u_r2r_dac_digital.sine_val[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _621_ (
    .CLK(clk),
    .D(_003_),
    .Q(\u_r2r_dac_digital.sine_val[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _622_ (
    .CLK(clk),
    .D(_004_),
    .Q(\u_r2r_dac_digital.sine_val[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _623_ (
    .CLK(clk),
    .D(_005_),
    .Q(\u_r2r_dac_digital.sine_val[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _624_ (
    .CLK(clk),
    .D(_006_),
    .Q(\u_r2r_dac_digital.sine_val[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _625_ (
    .CLK(clk),
    .D(_009_),
    .Q(\u_r2r_dac_digital.sine_val[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _626_ (
    .CLK(clk),
    .D(_010_),
    .Q(uo_out[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _627_ (
    .CLK(clk),
    .D(_011_),
    .Q(uo_out[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _628_ (
    .CLK(clk),
    .D(_012_),
    .Q(uo_out[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _629_ (
    .CLK(clk),
    .D(_013_),
    .Q(uo_out[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _630_ (
    .CLK(clk),
    .D(_014_),
    .Q(uo_out[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _631_ (
    .CLK(clk),
    .D(_015_),
    .Q(uo_out[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _632_ (
    .CLK(clk),
    .D(_016_),
    .Q(uo_out[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _633_ (
    .CLK(clk),
    .D(_017_),
    .Q(uo_out[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _634_ (
    .CLK(clk),
    .D(_018_),
    .Q(\u_r2r_dac_digital.code_reg[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _635_ (
    .CLK(clk),
    .D(_019_),
    .Q(\u_r2r_dac_digital.code_reg[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _636_ (
    .CLK(clk),
    .D(_020_),
    .Q(\u_r2r_dac_digital.code_reg[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _637_ (
    .CLK(clk),
    .D(_021_),
    .Q(\u_r2r_dac_digital.code_reg[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _638_ (
    .CLK(clk),
    .D(_022_),
    .Q(\u_r2r_dac_digital.code_reg[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _639_ (
    .CLK(clk),
    .D(_023_),
    .Q(\u_r2r_dac_digital.code_reg[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _640_ (
    .CLK(clk),
    .D(_024_),
    .Q(\u_r2r_dac_digital.code_reg[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _641_ (
    .CLK(clk),
    .D(_025_),
    .Q(\u_r2r_dac_digital.code_reg[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _642_ (
    .CLK(clk),
    .D(_026_),
    .Q(\u_r2r_dac_digital.cnt[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _643_ (
    .CLK(clk),
    .D(_027_),
    .Q(\u_r2r_dac_digital.cnt[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _644_ (
    .CLK(clk),
    .D(_028_),
    .Q(\u_r2r_dac_digital.cnt[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _645_ (
    .CLK(clk),
    .D(_029_),
    .Q(\u_r2r_dac_digital.cnt[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _646_ (
    .CLK(clk),
    .D(_030_),
    .Q(\u_r2r_dac_digital.cnt[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _647_ (
    .CLK(clk),
    .D(_031_),
    .Q(\u_r2r_dac_digital.cnt[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _648_ (
    .CLK(clk),
    .D(_032_),
    .Q(\u_r2r_dac_digital.cnt[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _649_ (
    .CLK(clk),
    .D(_033_),
    .Q(\u_r2r_dac_digital.cnt[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _650_ (
    .CLK(clk),
    .D(_034_),
    .Q(\u_r2r_dac_digital.presc[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _651_ (
    .CLK(clk),
    .D(_035_),
    .Q(\u_r2r_dac_digital.presc[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _652_ (
    .CLK(clk),
    .D(_036_),
    .Q(\u_r2r_dac_digital.presc[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _653_ (
    .CLK(clk),
    .D(_037_),
    .Q(\u_r2r_dac_digital.presc[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _654_ (
    .CLK(clk),
    .D(_038_),
    .Q(\u_r2r_dac_digital.presc[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _655_ (
    .CLK(clk),
    .D(_039_),
    .Q(\u_r2r_dac_digital.presc[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _656_ (
    .CLK(clk),
    .D(_007_),
    .Q(\u_r2r_dac_digital.presc[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _657_ (
    .CLK(clk),
    .D(_008_),
    .Q(\u_r2r_dac_digital.presc[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _658_ (
    .ZN(uio_oe[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _659_ (
    .ZN(uio_oe[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _660_ (
    .ZN(uio_oe[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _661_ (
    .ZN(uio_oe[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _662_ (
    .ZN(uio_oe[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _663_ (
    .ZN(uio_oe[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _664_ (
    .ZN(uio_oe[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _665_ (
    .ZN(uio_oe[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _666_ (
    .ZN(uio_out[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _667_ (
    .ZN(uio_out[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _668_ (
    .ZN(uio_out[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _669_ (
    .ZN(uio_out[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _670_ (
    .ZN(uio_out[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _671_ (
    .ZN(uio_out[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _672_ (
    .ZN(uio_out[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _673_ (
    .ZN(uio_out[7])
  );
  r2r_dac_analog u_analog (
    .dac_code(uo_out),
    .vout(ua[0])
  );
endmodule
