// r2r_dac_analog.v - generated by check_top_harden.py: the blackbox the
// synthesiser sees for the analog macro. Power pins exist only
// under USE_POWER_PINS (PDN_MACRO_CONNECTIONS ties them).
(* blackbox *)
module r2r_dac_analog (
`ifdef USE_POWER_PINS
    inout  wire vdd,
    inout  wire vss,
`endif
    input  wire [7:0] dac_code,
    inout  wire vout
);
endmodule
